### ISSUE TITLE
Pinging people if their nicks match words

### ISSUE THREAD

**Issue by ThePhilgrim** [Akuli/mantaray#106]
Not sure how this is solved in other irc clients, but could be annoying for people.

![Screenshot 2021-11-24 at 14 58 48](https://user-images.githubusercontent.com/76887896/143252293-6428bdac-5bec-4755-9709-f670079cf8cf.png)

**Comment by Akuli** [comment]
If your nickname is `am` or `seem`, you are asking for trouble, no matter what irc client you are using :)

IRC sends the messages as plain text. A ping is just someone's nickname mentioned in the text. The only way to prevent pinging a person named `am` is to not write messages that contain the word `am`.

**Comment by ThePhilgrim** [comment]
=D
