### ISSUE TITLE
Add option to hide connection messages for specific users (or something similar)

### ISSUE THREAD

**Issue by ThePhilgrim** [Akuli/mantaray#110]
This is going on the whole day, and it drives me crazy .

![Screenshot 2021-11-25 at 19 11 04](https://user-images.githubusercontent.com/76887896/143486732-1d264b6f-bc07-42e9-8f48-005dbf951d93.png)

**Comment by Akuli** [comment]
You can now right-click (or on mac, also control+click) `irc.libera.chat` and click "Server settings".
