### ISSUE TITLE
Client socket not closing when shutting down Mantaray

### ISSUE THREAD

**Issue by ThePhilgrim** [Akuli/mantaray#148]
To reproduce, use Mantatail commit a9b98e2.

Connect the client to the server, and then close Mantaray by clicking the X in the top corner.

The socket remains open.

**Comment by Akuli** [comment]
This is unlikely mantaray's fault. Regardless of how the client is closed, mantatail should close its socket when it's done using it. In fact, we recently improved this a lot in https://github.com/ThePhilgrim/MantaTail/pull/46.
