### ISSUE TITLE
KeyError when getting forwarded to channel when not connected with password

### ISSUE THREAD

**Issue by ThePhilgrim** [Akuli/mantaray#217]
To reproduce:

1. Connect to Libera without a valid login (nick/password)
2. Join `#css`(they have automatic forwarding to `#css-overflow` for non-registered users)

![Skärmavbild 2022-02-09 kl  20 50 16](https://user-images.githubusercontent.com/76887896/153279487-e1f97fbd-c223-45fa-8c47-85d36a3be14f.png)

**Comment by ThePhilgrim** [comment]
I didn't realize this was a duplicate issue. Sorry about that🙂

**Comment by Akuli** [comment]
It's ok, I create duplicate issues too :)
