### ISSUE TITLE
:sodium.libera.chat NOTICE * :*** No Ident response

### ISSUE THREAD

**Issue by Moosems** [Akuli/mantaray#282]
I was following the instructions for connecting to `irc.libera.chat` but when I used `nc irc.libera.chat 6667` I always got the following responses:
```yaml
Moosems:mantaray Moosems$ nc irc.libera.chat 6667
:sodium.libera.chat NOTICE * :*** Checking Ident
:sodium.libera.chat NOTICE * :*** Looking up your hostname...
:sodium.libera.chat NOTICE * :*** Found your hostname: (Not going to give for privacy reasons)
:sodium.libera.chat NOTICE * :*** No Ident response
```

What should I do?

**Comment by Akuli** [comment]
As the README says, you can run mantaray with `--verbose` to see what it does, but I agree that this should be explained in the README a bit more.

You need to send `NICK` and `USER` by typing to the terminal:

```
NICK Moosems
USER Moosems 0 * :Moosems
```

You should then see libera responding with lots more stuff. You can then join a channel and start sending messages:

```
JOIN ##learnpython
PRIVMSG ##learnpython :hello world
```

Also, remember when I said that IRC is super simple under the hood? This is how simple it is :)

**Comment by Akuli** [comment]
Turns out I have already explained how to do this in the README.
