### ISSUE TITLE
Crashes on close

### ISSUE THREAD

**Issue by Moosems** [Akuli/mantaray#284]
When the application is closed it gives the error:
```yaml
objc[12585]: Invalid or prematurely-freed autorelease pool 0x7f8d4c856410.
Abort trap: 6
```

**Comment by Akuli** [comment]
I think I once tried debugging this with ThePhilgrim (a mac user who has contributed a lot to mantaray).

**Comment by Moosems** [comment]
@Akuli I figured it out! `    irc_widget.bind("<Destroy>", lambda e: root.after_idle(root.destroy))` on line 126 of `__main__.py`. I tested the following code and it reproduces the issue:

```python
from tkinter import Tk

root = Tk()
root.after_idle(root.destroy)
root.mainloop()
```

**Comment by Moosems** [comment]
I found it when I tried using the same idea (thought of it on my own too) in DIP.
