### ISSUE TITLE
Cannot connect to irc.libera.chat even after I log in

### ISSUE THREAD

**Issue by Moosems** [Akuli/mantaray#285]
```yml
[09:56]	*	Connecting to irc.libera.chat port 6697...
[09:56]	*	Cannot connect (reconnecting in 5sec): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
```

Everytime I try to open the app the log is filled with this error message and I have done everything shown in the README. I have logged in using netcat but that doesn't seem to do anything

**Comment by Akuli** [comment]
Does not happen on my computer. Googling error message leads to https://stackoverflow.com/q/52805115

**Comment by Akuli** [comment]
Another alternative is to uncheck "Use SSL" in the connection dialog, which makes mantaray more like netcat. But that is an unencrypted connection, meaning that your ISP and anyone else who looks at your network traffic can see everything you type to IRC.

**Comment by Moosems** [comment]
> Does not happen on my computer. Googling error message leads to https://stackoverflow.com/q/52805115

I don't know how that helps

**Comment by Akuli** [comment]
You could connect without SSL for now. You can get to the connection dialog by right-clicking irc.libera.chat and going to "Server settings...". We can then figure out how to get SSL to work.

**Comment by Moosems** [comment]
> You could connect without SSL for now. You can get to the connection dialog by right-clicking irc.libera.chat and going to "Server settings...". We can then figure out how to get SSL to work.

I got that to work. After than I can't join any rooms the same way I did with netcat

**Comment by Akuli** [comment]
In IRC clients, the command is `/join ##learnpython`, but it should join automatically if you specify `##learnpython` in the connecting dialog. Does that not work?
