### ISSUE TITLE
Moosems suggestions

### ISSUE THREAD

**Issue by Akuli** [Akuli/mantaray#304]
- [x] **Most important:** remember size of user list
- [x] the entry should focus automatically when switching channels
- [ ] restart button in menubar (there is currently no menubar, except on macos where you always get a menubar)
- [x] dm's without having to ping first (or using `/msg`), maybe double-click or right-click in user list

**Comment by Moosems** [comment]
[] Right click user to get information (maybe from nisckserv), why or if they are away, and Dm option

**Comment by Akuli** [comment]
I don't think I will do a restart button. If you still want it, make a new issue and explain *why* you want it, what would you use it for, whta you currently do instead, and so on.
