### ISSUE TITLE
Long away reasons are hard to see in userlist

### ISSUE THREAD

**Issue by Akuli** [Akuli/mantaray#319]
![s](https://user-images.githubusercontent.com/18505570/230796601-1fc36b5c-df2b-47bf-a804-227b01e67ba4.png)

If I stretch the user list wide enough to fully see away reasons, the chat easily becomes unreadable:

![t](https://user-images.githubusercontent.com/18505570/230796700-52848d05-1ab1-4509-aae8-3a144a2f926f.png)

Some away reasons are pretty long. This one is 114 characters:

![s](https://user-images.githubusercontent.com/18505570/230796812-5cb845e2-36b8-40a2-89d0-a88072bdf80f.png)

Maybe it should show some kind of hover popup when you bring mouse over an away reason that doesn't fit.

**Comment by Moosems** [comment]
I would put it in the right click menu and it makes a pop up.

**Comment by Akuli** [comment]
@Moosems I made it show the away reason off to the side when hovered. What do you think?


https://user-images.githubusercontent.com/18505570/230886715-3c09fa50-2e34-48c1-a3b3-34aedf8cdf03.mp4

This approach is super simple to the user, but a downside is that it won't help when mantaray is at the right edge of your screen and there's no more space to the right.

**Comment by Moosems** [comment]
I think it's decent, if it's a simple top level without the exit bar at top it might have issues on max and i always keep Mantaray in my bottom right corner so it might be an issue but it certainly looks nice @Akuli.

**Comment by Akuli** [comment]
How about this? It no longer uses `Toplevel` and it doesn't extend beyond the mantaray window.

https://user-images.githubusercontent.com/18505570/230890629-f54b1ba4-53a8-4f69-beb4-b56e14bd75b2.mp4

**Comment by Moosems** [comment]
And if the name is at the bottom of the list?

**Comment by Akuli** [comment]
Already taken care of :)


https://user-images.githubusercontent.com/18505570/230891541-da64346e-ab3e-4ced-9667-6509ab334146.mp4
