### ISSUE TITLE
Weird channel look

### ISSUE THREAD

**Issue by Moosems** [Akuli/mantaray#322]
<img width="778" alt="Screen Shot 2023-04-10 at 7 53 03 AM" src="https://user-images.githubusercontent.com/95927277/230896873-65520c61-8bd0-413a-be57-940c81cf5115.png">

**Comment by Akuli** [comment]
I assume the weirdness is having lots of white borders around the entry and text widget? Those are the only two non-ttk widgets in mantaray. I should probably specify border colors and sizes for them.

**Comment by Moosems** [comment]
The white border and the weird treeview merge for the channel names.
