### ISSUE TITLE
light theme

### ISSUE THREAD

**Issue by Akuli** [Akuli/mantaray#327]
For the few monsters who don't like dark themes, such as Moosems, I think mantaray should provide a light theme. Two options (light or dark) should be enough for everyone.

The dark/light choice could be just a boolean in the JSON file. It doesn't need to be user-friendly or easily accessible from a GUI, because most mantaray users want a dark theme. That said it would be easy to make a checkbutton or similar with sv-ttk.

The biggest challenge will be the text widget. It has lots of different colors for errors, warnings, nicks, pings etc. They all need to look somewhat reasonable in light mode.

**Comment by Moosems** [comment]
I'm acquainted with messing with the json file.
