### ISSUE TITLE
Dropping Python 3.7 support

### ISSUE THREAD

**Issue by Akuli** [Akuli/mantaray#341]
It is now end of life.

**Comment by Moosems** [comment]
What does dropping it entail?

**Comment by Akuli** [comment]
Mostly searching for `3.7` or `(3, 7)` in the code and README, and removing any Python 3.7 specific things we find.

**Comment by Akuli** [comment]
It would also be good to mention in the README what version of Python is needed.

**Comment by Akuli** [comment]
I went through `git grep 7` and found nothing version-specific. README was updated in 32413039f9e44b1235559bcc3a06dfeb877d31d8.
