### ISSUE TITLE
can't close private message views

### ISSUE THREAD

**Issue by Akuli** [Akuli/mantaray#65]
If 10 people send me a private message, I have 10 PM views in the irc client that I can't close.

**Comment by ThePhilgrim** [comment]
Same with channels. If you join #foo, you cannot delete the channel if you want to leave it

**Comment by Akuli** [comment]
`/part #foo`

**Comment by ThePhilgrim** [comment]
> `/part #foo`. But you're right, it would be nice to have a GUI way to do this.

Fair enough! But yeah, I'd say right click -> leave/delete channel
