### ISSUE TITLE
redirecting to different channel

### ISSUE THREAD

**Issue by Akuli** [Akuli/mantaray#69]
As an unregistered user, if you try to `/join #css` on libera, you get errors

**Comment by ThePhilgrim** [comment]
Also, if you try `/join #homebrew`, you will notice that Libera tries to redirect you to `##homebrew`. However, as seen in the screenshot, this is a key error. It therefore doesn't show up in the channels list. Please tell me if you want me to make a new issue with this.

![Skärmavbild 2021-12-26 kl  19 55 48](https://user-images.githubusercontent.com/76887896/147417510-b1c559d3-e858-42ed-be1b-0b075f62f23c.png)

**Comment by Akuli** [comment]
This is likely the same problem. I will try both `#homebrew` and `#css` when fixing this.
