### ISSUE TITLE
Have to log in and join channels again after each git pull

### ISSUE THREAD

**Issue by ThePhilgrim** [Akuli/mantaray#92]
Can we in some way exclude the config file to be reset every time there is an update of Mantaray? That way we don't have to change our nicknames, add passwords and add channels again each time we pull

**Comment by Akuli** [comment]
The config files are backwards compatible all the way back to the oldest config files that ever existed. The only incompatibility was when I renamed from `irc-client` to `mantaray` and didn't remember to add code to check if there is a folder named `irc-client`. If you want the older config back, rename `appdirs.user_config_dir('irc-client', 'Akuli')` to `appdirs.user_config_dir('mantaray', 'Akuli')`.

**Comment by Akuli** [comment]
I improved the situation slightly in 436bc62, but that only applies on computers where irc-client was used only before the rename to mantaray.

**Comment by ThePhilgrim** [comment]
I had to readd everything when you changed to mantaray, and after pulling today
