### ISSUE TITLE
Dark Theme/GUI enhancements MACOS

### ISSUE THREAD

**Issue by ThePhilgrim** [Akuli/mantaray#99]
[https://imgur.com/a/WTSIHMT](https://imgur.com/a/WTSIHMT)
- [x] Dark grey in user/channel list stops after last user/channel - Make the same color take up the whole column
- [x] Make chat window color match the colors of the sidebar #170 
- [ ] Make the text written by other users a slightly different color from ones own messages
- [x] Make color of "system text" (ex. "FooBar has joined") different from chat messages #225

**Comment by Akuli** [comment]
>Dark grey in user/channel list stops after last user/channel - Make the same color take up the whole column

IRC client uses https://github.com/TkinterEP/ttkthemes for this. Please report it there.

> Make chat window color match the colors of the sidebar

Would you like to make a pull request? The colors are defined in `colors.py`.

**Comment by Akuli** [comment]
I managed to change the dark grey to match the rest:
```
>>> tv.tk.eval("ttk::style lookup Treeview -background")
'#424242'
>>> tv.tk.eval("ttk::style lookup Treeview -fieldbackground")
'#626262'
>>> tv.tk.eval("ttk::style configure Treeview -fieldbackground #424242")
''
```

**Comment by rdbende** [comment]
> Dark grey in user/channel list stops after last user/channel - Make the same color take up the whole column

Completed with #326

**Comment by Akuli** [comment]
There is only one item remaining now: making messages sent by yourself and others slightly different color. If someone still wants it, feel free to make a separate issue.
